# Paths to use for the log files
logs:
  # The main log for all messages
  main: atc.log

  # Log for only radio messages
  transcript: transcript.log

# Corrade configuration
corrade:
  # The Corrade MQTT server URL
  mqtt: https://127.0.0.1:1883

  # The Corrade group for commands
  group: MyGroup

  # The corrade password for commands
  password: MyGroupPassword

  # The language used for scripts, WAS or JSON
  language: WAS

# GridTalkie config
gridtalkie:
  # Mapping of GridTalkie channels to the SL text channels that the viewer
  # will use to interact with them.
  channels:
    12270-Gridwide ATC: 11
    11920-BLAKE: 12

# ATC bot configuration
atc:
  # The handle to use on GridTalkie
  handle: ICAO TOWER

  # The prefix that messages must start with for the bot to reply
  prefix: ICAO

  # Extra information given with generic departure clearances
  departureInfo: ""

  # Extra information given with runway departure clearances
  departureInfoRunway: ""

  # Extra information given with helipad departure clearances
  departureInfoHelipad: ""

  # Extra information given for approach messages
  approachInfo: ""

  # Extra information given with generic landing clearances
  landingInfo: ""

  # Extra information given with runway landing clearances
  landingInfoRunway: ""

  # Extra information given with helipad landing clearances
  landingInfoHelipad: ""

# Shergood METAR config
metar:
  # The ICAO of the airport
  icao: ICAO
  
  # How often in milliseconds to update the METAR data
  update: 300000

# Region for squawk code generation
squawk:
  current_region: "corsica"
  # Region can be one of the following:
  # - corsica
  # - gaeta v
  # - nautilus
  # - satori
  # - blake sea
  # - heterocera
  # - sansara
  # - jeogot
  # - bellisseria
  # - military/special groups
  regions:
    corsica:
      min: 0001
      max: 0660
    gaeta:
      min: 0661
      max: 1320
    nautilus:
      min: 1321
      max: 1980
    satori:
      min: 1981
      max: 2640
    blake_sea:
      min: 2641
      max: 3300
    heterocera:
      min: 3301
      max: 3960
    sansara:
      min: 3961
      max: 4620
    jeogot:
      min: 4621
      max: 5280
    bellisseria:
      min: 5281
      max: 5940
    military:
      min: 5941
      max: 6659
# - Having a squawk code of 6660 seems to be superstitious, so it is not used.
# - The squawk code 0000 is reserved for emergencies, so it is not used.
# - Sqauwk codes in the 7000 range are reserved for special use, so they are not used.
